version: '3'
services: 
  web:
    environment: 
      - CHOKIDAR_USESPOLLING=true
    build: 
      context: .
      dockerfile: Dockerfile.dev
      
    ports:
      - "3000:3000"
    volumes: 
      - /app/node-modules
      - .:/app
  tests: #when using compose up, tests will start 
    environment: 
      - CHOKIDAR_USESPOLLING=true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node-modules
      - .:/app
    command: ["npm", "run", "test"]
    